BaseUrl = "https://github.com/zhenzhaoya/locust/" # Base url, Can be empty.
HttpFile = "../http/demo.http" # HTTP request profile
Port = 8080 
UserCount = 1
MinWait = 10000 # Minimum time interval in milliseconds
MaxWait = 10000 # Maximum time interval in milliseconds