### 
GET <%=BaseUrl %>/blob/master/http/demo.http
Referer: <%=BaseUrl %>/blob/master/http/demo.http

<%
  StatusCode == 200
%>

### START
POST <%=BaseUrl %>/blob/master/http/demo.http
Referer: <%=BaseUrl %>/blob/master/http/demo.http

{"name":"demo","pwd":"123456"}

<%
  StatusCode != 200
%>

